lib: [
  "_build/install/default/lib/kawa/META"
  "_build/install/default/lib/kawa/dune-package"
  "_build/install/default/lib/kawa/lang/abstract_syntax.ml" {"lang/abstract_syntax.ml"}
  "_build/install/default/lib/kawa/lang/allocator.ml" {"lang/allocator.ml"}
  "_build/install/default/lib/kawa/lang/context.ml" {"lang/context.ml"}
  "_build/install/default/lib/kawa/lang/debug.ml" {"lang/debug.ml"}
  "_build/install/default/lib/kawa/lang/environment.ml" {"lang/environment.ml"}
  "_build/install/default/lib/kawa/lang/interpreter.ml" {"lang/interpreter.ml"}
  "_build/install/default/lib/kawa/lang/lang.a" {"lang/lang.a"}
  "_build/install/default/lib/kawa/lang/lang.cma" {"lang/lang.cma"}
  "_build/install/default/lib/kawa/lang/lang.cmi" {"lang/lang.cmi"}
  "_build/install/default/lib/kawa/lang/lang.cmt" {"lang/lang.cmt"}
  "_build/install/default/lib/kawa/lang/lang.cmx" {"lang/lang.cmx"}
  "_build/install/default/lib/kawa/lang/lang.cmxa" {"lang/lang.cmxa"}
  "_build/install/default/lib/kawa/lang/lang.ml" {"lang/lang.ml"}
  "_build/install/default/lib/kawa/lang/lang__Abstract_syntax.cmi" {"lang/lang__Abstract_syntax.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Abstract_syntax.cmt" {"lang/lang__Abstract_syntax.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Abstract_syntax.cmx" {"lang/lang__Abstract_syntax.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Allocator.cmi" {"lang/lang__Allocator.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Allocator.cmt" {"lang/lang__Allocator.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Allocator.cmx" {"lang/lang__Allocator.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Context.cmi" {"lang/lang__Context.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Context.cmt" {"lang/lang__Context.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Context.cmx" {"lang/lang__Context.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Debug.cmi" {"lang/lang__Debug.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Debug.cmt" {"lang/lang__Debug.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Debug.cmx" {"lang/lang__Debug.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Environment.cmi" {"lang/lang__Environment.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Environment.cmt" {"lang/lang__Environment.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Environment.cmx" {"lang/lang__Environment.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Interpreter.cmi" {"lang/lang__Interpreter.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Interpreter.cmt" {"lang/lang__Interpreter.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Interpreter.cmx" {"lang/lang__Interpreter.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Lexer.cmi" {"lang/lang__Lexer.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Lexer.cmt" {"lang/lang__Lexer.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Lexer.cmx" {"lang/lang__Lexer.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Method.cmi" {"lang/lang__Method.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Method.cmt" {"lang/lang__Method.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Method.cmx" {"lang/lang__Method.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Parser.cmi" {"lang/lang__Parser.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Parser.cmt" {"lang/lang__Parser.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Parser.cmti" {"lang/lang__Parser.cmti"}
  "_build/install/default/lib/kawa/lang/lang__Parser.cmx" {"lang/lang__Parser.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Symbol.cmi" {"lang/lang__Symbol.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Symbol.cmt" {"lang/lang__Symbol.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Symbol.cmx" {"lang/lang__Symbol.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Symbol_resolver.cmi" {"lang/lang__Symbol_resolver.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Symbol_resolver.cmt" {"lang/lang__Symbol_resolver.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Symbol_resolver.cmx" {"lang/lang__Symbol_resolver.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Type.cmi" {"lang/lang__Type.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Type.cmt" {"lang/lang__Type.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Type.cmx" {"lang/lang__Type.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Type_checker.cmi" {"lang/lang__Type_checker.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Type_checker.cmt" {"lang/lang__Type_checker.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Type_checker.cmx" {"lang/lang__Type_checker.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Type_error.cmi" {"lang/lang__Type_error.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Type_error.cmt" {"lang/lang__Type_error.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Type_error.cmx" {"lang/lang__Type_error.cmx"}
  "_build/install/default/lib/kawa/lang/lexer.ml" {"lang/lexer.ml"}
  "_build/install/default/lib/kawa/lang/method.ml" {"lang/method.ml"}
  "_build/install/default/lib/kawa/lang/parser.ml" {"lang/parser.ml"}
  "_build/install/default/lib/kawa/lang/parser.mli" {"lang/parser.mli"}
  "_build/install/default/lib/kawa/lang/symbol.ml" {"lang/symbol.ml"}
  "_build/install/default/lib/kawa/lang/symbol_resolver.ml" {"lang/symbol_resolver.ml"}
  "_build/install/default/lib/kawa/lang/type.ml" {"lang/type.ml"}
  "_build/install/default/lib/kawa/lang/type_checker.ml" {"lang/type_checker.ml"}
  "_build/install/default/lib/kawa/lang/type_error.ml" {"lang/type_error.ml"}
  "_build/install/default/lib/kawa/opam"
]
libexec: [
  "_build/install/default/lib/kawa/lang/lang.cmxs" {"lang/lang.cmxs"}
]
bin: [
  "_build/install/default/bin/kawa.interpreter"
  "_build/install/default/bin/kawa.test.typechecker"
]
doc: [
  "_build/install/default/doc/kawa/README.md"
]
