lib: [
  "_build/install/default/lib/kawa/META"
  "_build/install/default/lib/kawa/dune-package"
  "_build/install/default/lib/kawa/lang/ast.ml" {"lang/ast.ml"}
  "_build/install/default/lib/kawa/lang/call.ml" {"lang/call.ml"}
  "_build/install/default/lib/kawa/lang/ctx.ml" {"lang/ctx.ml"}
  "_build/install/default/lib/kawa/lang/frame.ml" {"lang/frame.ml"}
  "_build/install/default/lib/kawa/lang/lang.a" {"lang/lang.a"}
  "_build/install/default/lib/kawa/lang/lang.cma" {"lang/lang.cma"}
  "_build/install/default/lib/kawa/lang/lang.cmi" {"lang/lang.cmi"}
  "_build/install/default/lib/kawa/lang/lang.cmt" {"lang/lang.cmt"}
  "_build/install/default/lib/kawa/lang/lang.cmx" {"lang/lang.cmx"}
  "_build/install/default/lib/kawa/lang/lang.cmxa" {"lang/lang.cmxa"}
  "_build/install/default/lib/kawa/lang/lang.ml" {"lang/lang.ml"}
  "_build/install/default/lib/kawa/lang/lang__Ast.cmi" {"lang/lang__Ast.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Ast.cmt" {"lang/lang__Ast.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Ast.cmx" {"lang/lang__Ast.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Call.cmi" {"lang/lang__Call.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Call.cmt" {"lang/lang__Call.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Call.cmx" {"lang/lang__Call.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Ctx.cmi" {"lang/lang__Ctx.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Ctx.cmt" {"lang/lang__Ctx.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Ctx.cmx" {"lang/lang__Ctx.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Frame.cmi" {"lang/lang__Frame.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Frame.cmt" {"lang/lang__Frame.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Frame.cmx" {"lang/lang__Frame.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Load.cmi" {"lang/lang__Load.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Load.cmt" {"lang/lang__Load.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Load.cmx" {"lang/lang__Load.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Sym.cmi" {"lang/lang__Sym.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Sym.cmt" {"lang/lang__Sym.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Sym.cmx" {"lang/lang__Sym.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Symbol_resolv.cmi" {"lang/lang__Symbol_resolv.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Symbol_resolv.cmt" {"lang/lang__Symbol_resolv.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Symbol_resolv.cmx" {"lang/lang__Symbol_resolv.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Type.cmi" {"lang/lang__Type.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Type.cmt" {"lang/lang__Type.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Type.cmx" {"lang/lang__Type.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Type_check.cmi" {"lang/lang__Type_check.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Type_check.cmt" {"lang/lang__Type_check.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Type_check.cmx" {"lang/lang__Type_check.cmx"}
  "_build/install/default/lib/kawa/lang/lang__Type_error.cmi" {"lang/lang__Type_error.cmi"}
  "_build/install/default/lib/kawa/lang/lang__Type_error.cmt" {"lang/lang__Type_error.cmt"}
  "_build/install/default/lib/kawa/lang/lang__Type_error.cmx" {"lang/lang__Type_error.cmx"}
  "_build/install/default/lib/kawa/lang/load.ml" {"lang/load.ml"}
  "_build/install/default/lib/kawa/lang/sym.ml" {"lang/sym.ml"}
  "_build/install/default/lib/kawa/lang/symbol_resolv.ml" {"lang/symbol_resolv.ml"}
  "_build/install/default/lib/kawa/lang/type.ml" {"lang/type.ml"}
  "_build/install/default/lib/kawa/lang/type_check.ml" {"lang/type_check.ml"}
  "_build/install/default/lib/kawa/lang/type_error.ml" {"lang/type_error.ml"}
  "_build/install/default/lib/kawa/opam"
]
libexec: [
  "_build/install/default/lib/kawa/lang/lang.cmxs" {"lang/lang.cmxs"}
]
bin: [
  "_build/install/default/bin/kawa.interpreter"
]
doc: [
  "_build/install/default/doc/kawa/README.md"
]
